# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CausalInferenceModel": "00_causalinference.ipynb",
         "metalearner_cls_dict": "00_causalinference.ipynb",
         "metalearner_reg_dict": "00_causalinference.ipynb",
         "Autocoder": "01_autocoder.ipynb",
         "list2chunks": "02_analyzers.ipynb",
         "ZeroShotClassifier": "02_analyzers.ipynb",
         "TextEncoder": "02_analyzers.ipynb",
         "TopicModel": "02_analyzers.ipynb",
         "DEFAULT_TOKEN_PATTERN": "02_analyzers.ipynb"}

modules = ["causalinference.py",
           "autocoder.py",
           "analyzers.py"]

doc_url = "https://amaiya.github.io/causalnlp/"

git_url = "https://github.com/amaiya/causalnlp/tree/main/"

def custom_doc_links(name): return None
